/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.teamnf.sensors;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MPU6050Test {
    @Test void test() {}
}
